# Generated by Django 5.0.4 on 2024-04-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.TextField()),
                ('img_dp', models.ImageField(upload_to='static/images/')),
                ('title', models.TextField()),
                ('cap1', models.TextField()),
                ('cap2', models.TextField()),
            ],
        ),
    ]
