# Generated by Django 5.0.4 on 2024-04-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='cap1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='cap2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='iframe',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
