# Generated by Django 5.0.4 on 2024-04-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_youtube_cap1_alter_youtube_cap2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='img_dp',
            field=models.CharField(max_length=200),
        ),
    ]
