# Generated by Django 5.0.4 on 2024-04-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_youtube_img_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='iframe',
            field=models.TextField(),
        ),
    ]
