# Generated by Django 5.0.4 on 2024-04-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_youtube_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='iframe',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
